### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Yomodo**

### CODE REVIEW

**Comment by Yomodo** [comment]
@alphaleonis Bug fix for master branch.

**Comment by alphaleonis** [comment]
You comitted and pushed it to master already? Why did you leave a pull-request for the merge to develop in that case?

**Comment by Yomodo** [comment]
Merging from Master to Develop should be the next step, right?

**Comment by alphaleonis** [comment]
Ah, yes, of course. I thought you had left it for me to merge/review. Didn't realize you had just pushed it. ;)

**Pull request merged**
